---
roles:
  - name: lablabs.rke2
collections:
  - name: pokerops.rke2
    source: .
    type: dir
  - name: nephelaiio.plugins
  - name: nephelaiio.consul
  - name: nephelaiio.libvirt
  - name: amazon.aws
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: community.postgresql
  - name: kubernetes.core
