---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.0
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - 1.1.1.1
            - 8.8.8.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
