---
# Required as opposed to inline definitions in molecule.yml as molecule's
# provisioner.inventory.links are mutually exclusive with inline declarations
# in molecule.yml
all:
  vars:
    # Required rke2 params
    rke2_cluster_name: rke2.pokerops.net
    rke2_ippool_private: "{{ molecule_pool_private }}"
    rke2_ippool_public: "{{ molecule_pool_public }}"
    rke2_api_url: "https://api.{{ rke2_cluster_name }}:6443"
    rke2_token: "secret"
    # Test rke2 params
    rke2_skip_deploy: true
    rke2_monitoring_deploy: true
    rke2_longhorn_replica_count: 2
