---
- name: Gather cluster facts
  hosts: all
  gather_facts: true

- name: Verify cluster BGP configuration
  hosts: localhost
  any_errors_fatal: true
  vars:
    ingress_namespace: nginx
  tasks:
    - name: Verify BGP Peer resources exist
      block:
        - name: Query BGPPeer resources
          kubernetes.core.k8s_info:
            api_version: metallb.io/v1beta2
            kind: BGPPeer
            namespace: metallb-system
            kubeconfig: "{{ molecule_local_kubeconfig }}"
          register: _bgp_peers

        - name: Verify BGPPeer
          ansible.builtin.assert:
            that: _bgp_peers.resources | length > 0
            fail_msg: "Found no BGPPeers"

    - name: Verify BGP Advertisement resource exists
      block:
        - name: Query BGPAdvertisement resources
          kubernetes.core.k8s_info:
            api_version: metallb.io/v1beta1
            kind: BGPAdvertisement
            namespace: metallb-system
            kubeconfig: "{{ molecule_local_kubeconfig }}"
          register: _bgp_advertisements
          changed_when: false

        - name: Verify BGPAdvertisement
          ansible.builtin.assert:
            that: _bgp_advertisements.resources | selectattr('metadata.name', 'equalto', 'metallb') | length == 1
            fail_msg: "Found no BGPAdvertisements"

        - name: Query L2Advertisement resources
          kubernetes.core.k8s_info:
            api_version: metallb.io/v1beta2
            kind: L2Advertisement
            namespace: metallb-system
            kubeconfig: "{{ molecule_local_kubeconfig }}"
          register: _l2_advertisements
          changed_when: false

        - name: Verify no L2Advertisement resources exist
          ansible.builtin.assert:
            that: _l2_advertisements.resources | length == 0
            fail_msg: "Found L2Advertisement resources in BGP mode: {{ _l2_advertisements.resources | map(attribute='metadata.name') }}"

    - name: Verify ingress controller LoadBalancer services
      block:
        - name: Query Ingress controller services
          kubernetes.core.k8s_info:
            kind: Service
            namespace: "{{ ingress_namespace }}"
            kubeconfig: "{{ molecule_local_kubeconfig }}"
          vars:
            _lbs: "{{ _ingress_service_query.resources | selectattr('spec.type', 'equalto', 'LoadBalancer') }}"
          register: _ingress_service_query
          retries: 15
          delay: 20
          failed_when: _lbs | length != 2
          changed_when: false

        - name: Set Ingress controller facts
          ansible.builtin.set_fact:
            _ingress_services: "{{ _ingress_service_query.resources | selectattr('spec.type', 'equalto', 'LoadBalancer') }}"

        - name: Verify LoadBalancer services
          ansible.builtin.assert:
            that: _ingress_services | length == 2
            fail_msg: "Expected 2 Ingress controllers, found {{ _ingress_services | length }}"

        - name: Verify Ingress controllers have External IPs
          ansible.builtin.assert:
            that:
              - _service.status.loadBalancer.ingress is defined
              - _service.status.loadBalancer.ingress | length > 0
              - _service.status.loadBalancer.ingress[0].ip is defined
            fail_msg: "Service {{ item }} has no External IP assigned"
            success_msg: "Service {{ item }} has External IP {{ _service.status.loadBalancer.ingress[0].ip }}"
          vars:
            _service: "{{ _ingress_services | selectattr('metadata.name', 'equalto', item) | first }}"
          loop: "{{ _ingress_services | map(attribute='metadata.name') }}"
          retries: 15
          delay: 20

        - name: Record Ingress IPs
          ansible.builtin.set_fact:
            _ingress_ips: "{{ _ingress_services | map(attribute='status.loadBalancer.ingress') | map('first') | map(attribute='ip') }}"

        - name: Debug ingress IPs
          ansible.builtin.debug:
            var: _ingress_ips

    - name: Verify cluster pod status
      ansible.builtin.shell:
        cmd: "/var/lib/rancher/rke2/bin/kubectl get pod -A -o json | jq '.items'"
      vars:
        _pod_data: "{{ _pod_data.stdout | from_json }}"
        _pod_status: "{{ _pod_data | selectattr('status', 'defined') }}"
        _pod_phase: "{{ _pod_status | selectattr('status.phase', 'defined') }}"
        _pod_completed: "{{ _pod_phase | rejectattr('status.phase', 'equalto', 'Running') }}"
        _pod_failed: "{{ _pod_completed | rejectattr('status.phase', 'equalto', 'Succeeded') }}"
      register: _pod_data
      retries: 15
      delay: 20
      until: _pod_failed | length == 0
      failed_when:
        - (_pod_status | length) != (_pod_data | length)
        - (_pod_phase | length) != (_pod_data | length)
        - _pod_failed | length > 0
      changed_when: false

    - name: Verify FRR container is running
      block:
        - name: Query FRR container status
          community.docker.docker_container_info:
            name: frr
          register: _frr_container_query
          changed_when: false

        - name: Assert FRR container is running
          ansible.builtin.assert:
            that: _status == 'running'
            fail_msg: "FRR container is in state {{ _status }}"
          vars:
            _status: "{{ _frr_container_query.container.State.Status }}"

    - name: Verify FRR BGP daemon is active
      block:
        - name: Query BGP summary
          ansible.builtin.shell:
            cmd: "docker exec frr vtysh -c 'show bgp summary json'"
          register: _bgp_summary_query
          changed_when: false

        - name: Parse BGP neighbor data
          ansible.builtin.set_fact:
            _bgp_summary: "{{ _bgp_summary_query.stdout }}"

        - name: Verify neighbor list
          ansible.builtin.assert:
            that:
              - _neighbors | length > 0
              - _neighbors | symmetric_difference(_nodes) | length == 0
            fail_msg: "Found neighbor mismatch, expected {{ _nodes }}, got {{ _neighbors }} "
            success_msg: "All neighbors are registered in bgp summary: {{ _neighbors }}"
          vars:
            _neighbors: "{{ _bgp_summary.ipv4Unicast.peers.values() | map(attribute='hostname') }}"
            _nodes: "{{ groups['all'] }}"

        - name: Verify neighbor state
          ansible.builtin.assert:
            that:
              - _neighbors | length > 0
              - _neighbors_ok | length > 0
              - _neighbors_ko | length == 0
            fail_msg: "The following neighbors are in a failed state: {{ _neighbors_ko | map(attribute='hostname') }}"
            success_msg: "All neighbors have established adjacencies: {{ _neighbors | map(attribute='hostname') }}"
          vars:
            _neighbors: "{{ _bgp_summary.ipv4Unicast.peers.values() }}"
            _neighbors_ok: "{{ _neighbors | selectattr('state', 'equalto', 'Established') }}"
            _neighbors_ko: "{{ _neighbors | rejectattr('state', 'equalto', 'Established') }}"

    - name: Verify BGP route propagation
      block:
        - name: Query BGP IPv4 unicast routes
          ansible.builtin.shell:
            cmd: "docker exec frr vtysh -c 'show bgp ipv4 unicast json'"
          vars:
            _bgp_routes: "{{ _bgp_route_query.stdout | from_json }}"
            _ingress_routes: "{{ _ingress_ips | product(['32']) | map('join', '/') }}"
          register: _bgp_route_query
          retries: 15
          delay: 20
          until:
            - _bgp_routes.routes.keys() | length > 0
            - _bgp_routes.routes.keys() | symmetric_difference(_ingress_routes) | length == 0
          changed_when: false

        - name: Parse BGP IPv4 unicast data
          ansible.builtin.set_fact:
            _bgp_routes: "{{ _bgp_route_query.stdout }}"
            _ingress_routes: "{{ _ingress_ips | product(['32']) | map('join', '/') }}"

        - name: Verify ingress IPs exist in BGP table
          ansible.builtin.assert:
            that:
              - _routes | length > 0
              - _routes | symmetric_difference(_ingress_routes) | length == 0
            fail_msg: "Found BGP route mismatch, expected {{ _ingress_routes }}, got {{ _routes }}"
            success_msg: "Found BGP routes for ingress ips {{ _ingress_routes }}"
          vars:
            _routes: "{{ _bgp_routes.routes.keys() }}"

        - name: Verify route validity
          ansible.builtin.assert:
            that:
              - _routes | length > 0
              - _routes_best | length > 0
            fail_msg: "No best route registered for prefix {{ item }}"
            success_msg: "Best path found for prefix {{ item }} through peer {{ (_routes_best | first).peerId }}"
          vars:
            _routes: "{{ _bgp_routes.routes[item] }}"
            _routes_valid: "{{ _routes | selectattr('valid', 'defined') | selectattr('valid', 'equalto', true) }}"
            _routes_best: "{{ _routes_valid | selectattr('bestpath', 'defined') | selectattr('bestpath', 'equalto', true) }}"
          loop: "{{ _ingress_routes }}"

        - name: Verify route next hops
          ansible.builtin.assert:
            that:
              - _routes_ok | length > 0
              - _routes_ko | length == 0
            fail_msg: "No next hops found for routes from peers {{ _routes_ko | map(attribute='peerId') }}"
            success_msg: "Found next hops for {{ item }}: {{ _routes_ok | map(attribute='peerId') }}"
          vars:
            _routes: "{{ _bgp_routes.routes[item] }}"
            _routes_ok: "{{ _routes | rejectattr('nexthops', 'equalto', []) }}"
            _routes_ko: "{{ _routes | selectattr('nexthops', 'equalto', []) }}"
          loop: "{{ _ingress_routes }}"

    - name: Verify FRR route table
      block:
        - name: Query FRR routes
          ansible.builtin.shell:
            cmd: "docker exec frr ip -j -d route show"
          vars:
            _routes_data: "{{ _frr_route_query.stdout | from_json }}"
            _routes_bgp: "{{ _routes_data | selectattr('protocol', 'equalto', 'bgp') }}"
            _routes_ingress: "{{ _routes_bgp | selectattr('dst', 'in', _ingress_ips) }}"
            _routes_nexthops: "{{ _routes_ingress | selectattr('nexthops', 'defined') }}"
          register: _frr_route_query
          changed_when: false
          retries: 15
          delay: 20
          until: _routes_nexthops | length == _ingress_ips | length

        - name: Parse FRR route data
          ansible.builtin.set_fact:
            _frr_routes: "{{ _routes_dict }}"
          vars:
            _routes_data: "{{ _frr_route_query.stdout | from_json }}"
            _routes_bgp: "{{ _routes_data | selectattr('protocol', 'equalto', 'bgp') }}"
            _routes_ingress: "{{ _routes_bgp | selectattr('dst', 'in', _ingress_ips) }}"
            _routes_wnexthops: "{{ _routes_ingress | selectattr('nexthops', 'defined') }}"
            _routes_dsts: "{{ _routes_wnexthops | map(attribute='dst') }}"
            _routes_nexthops: "{{ _routes_wnexthops | map(attribute='nexthops') }}"
            _routes_gateways: "{{ _routes_nexthops | map('map', attribute='gateway') }}"
            _routes_dict: "{{ _routes_dsts | zip(_routes_gateways) | nephelaiio.plugins.to_dict }}"

        - name: Debug FRR route data
          ansible.builtin.debug:
            var: _frr_routes

        - name: Verify ingress routes on FRR table
          ansible.builtin.assert:
            that: _gateways | intersect(_nodes) | length == _nodes | length
            fail_msg: "Routes missing for address {{ item }}, {{ _nodes | difference(_gateways) }}"
            success_msg: "Routes installed for address {{ item }} with gateways {{ _gateways }}"
          vars:
            _gateways: "{{ _frr_routes[item] }}"
            _nodes: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
          loop: "{{ _frr_routes.keys() }}"

    - name: Verify local route table
      block:
        - name: Query local routes
          ansible.builtin.shell:
            cmd: "ip -j -d route show"
          register: _host_route_query
          changed_when: false
          vars:
            _routes_data: "{{ _host_route_query.stdout | from_json }}"
            _routes_bgp: "{{ _routes_data | selectattr('protocol', 'equalto', 'bgp') }}"
            _routes_ingress: "{{ _routes_bgp | selectattr('dst', 'in', _ingress_ips) }}"
            _routes_nexthops: "{{ _routes_ingress | selectattr('nexthops', 'defined') }}"
          retries: 15
          delay: 20
          until: _routes_nexthops | length == _ingress_ips | length

        - name: Parse local route data
          ansible.builtin.set_fact:
            _local_routes: "{{ _routes_dict }}"
          vars:
            _routes_data: "{{ _frr_route_query.stdout | from_json }}"
            _routes_ingress: "{{ _routes_data | selectattr('dst', 'in', _ingress_ips) }}"
            _routes_wnexthops: "{{ _routes_ingress | selectattr('nexthops', 'defined') }}"
            _routes_dsts: "{{ _routes_wnexthops | map(attribute='dst') }}"
            _routes_nexthops: "{{ _routes_wnexthops | map(attribute='nexthops') }}"
            _routes_gateways: "{{ _routes_nexthops | map('map', attribute='gateway') }}"
            _routes_dict: "{{ _routes_dsts | zip(_routes_gateways) | nephelaiio.plugins.to_dict }}"

        - name: Debug local route data
          ansible.builtin.debug:
            var: _local_routes

        - name: Verify ingress routes on local table
          ansible.builtin.assert:
            that: _gateways | intersect(_nodes) | length == _nodes | length
            fail_msg: "Routes missing for address {{ item }}, {{ _nodes | difference(_gateways) }}"
            success_msg: "Routes installed for address {{ item }} with gateways {{ _gateways }}"
          vars:
            _gateways: "{{ _local_routes[item] }}"
            _nodes: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
          loop: "{{ _local_routes.keys() }}"

    - name: Verify HTTP/HTTPS connectivity via ingress
      block:
        - name: Query ingress namespaces
          ansible.builtin.shell:
            cmd: "KUBECONFIG={{ molecule_local_kubeconfig }} kubectl get ingress -A -o=jsonpath='{.items[*].metadata.namespace}'"
          register: _ingress_namespace_query
          changed_when: false

        - name: Parse namespace data
          ansible.builtin.set_fact:
            _ingress_namespaces: "{{ _ingress_namespace_query.stdout | split(' ') }}"

        - name: Query ingress data
          kubernetes.core.k8s_info:
            kind: Ingress
            namespace: "{{ item }}"
            kubeconfig: "{{ molecule_local_kubeconfig }}"
          loop: "{{ _ingress_namespaces }}"
          register: _ingress_query
          changed_when: false

        - name: Verify ingress endpoints
          ansible.builtin.uri:
            url: "https://{{ _address.ip }}"
            method: GET
            headers:
              Host: "{{ _host }}"
            validate_certs: false
            timeout: 5
            status_code:
              - 200
              - 301
              - 302
              - 307
              - 308
          vars:
            _host: "{{ (item.spec.tls | first).hosts | first }}"
            _address: "{{ item.status.loadBalancer.ingress | first }}"
          loop_control:
            label: "{{ _host }}"
          loop: "{{ _ingress_query.results | map(attribute='resources') | flatten }}"
          changed_when: false
