---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: rke2-${MOLECULE_SCENARIO_NAME}-server-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 4
    mem: 8
    groups:
      - rke2_server
  - name: rke2-${MOLECULE_SCENARIO_NAME}-agent-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    groups:
      - rke2_agent
  - name: rke2-${MOLECULE_SCENARIO_NAME}-agent-02
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    groups:
      - rke2_agent
  - name: rke2-${MOLECULE_SCENARIO_NAME}-agent-03
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 2
    mem: 4
    groups:
      - rke2_agent
provisioner:
  name: ansible
  playbooks:
    create: ../common/libvirt.yml
    prepare: ../common/prepare.yml
    converge: ../common/bgp.yml
    destroy: ../common/destroy.yml
    side_effect: ../common/deploy.yml
    verify: ../common/verify/bgp.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    links:
      group_vars: ../common/group_vars
      hosts: ./hosts.yml
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - side_effect
    - verify
