---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    chart: mariadb-operator
    repoURL: ghcr.io/mariadb-operator/charts
    targetRevision: "26.6.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
