---
- name: Cleanup AWS resources after testing
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if S3 bucket exists
      amazon.aws.s3_bucket_info:
        name: "{{ rke2_velero_s3_bucket }}"
      register: bucket_check
      ignore_errors: true

    - name: Cleanup S3 bucket resources
      when: bucket_check is succeeded and rke2_velero_s3_bucket in (bucket_check.buckets | map(attribute='name') | list)
      block:
        - name: Empty S3 bucket before deletion
          block:
            - name: List all objects in bucket
              amazon.aws.s3_object_info:
                bucket_name: "{{ rke2_velero_s3_bucket }}"
              register: bucket_objects
              ignore_errors: true

            - name: Delete all objects in bucket
              amazon.aws.s3_object:
                bucket: "{{ rke2_velero_s3_bucket }}"
                object: "{{ item }}"
                mode: delobj
              loop: "{{ bucket_objects.s3_keys | default([]) }}"
              when: bucket_objects.s3_keys is defined
              ignore_errors: true

            - name: List all object versions in bucket
              amazon.aws.s3_object_info:
                bucket_name: "{{ rke2_velero_s3_bucket }}"
                list_versions: true
              register: bucket_versions
              ignore_errors: true

            - name: Delete all object versions in bucket
              amazon.aws.s3_object:
                bucket: "{{ rke2_velero_s3_bucket }}"
                object: "{{ item.key }}"
                version_id: "{{ item.version_id }}"
                mode: delobj
              loop: "{{ bucket_versions.s3_keys | default([]) }}"
              when:
                - bucket_versions.s3_keys is defined
                - item.version_id is defined
                - item.version_id != 'null'
              ignore_errors: true

            - name: Delete all delete markers in bucket
              amazon.aws.s3_object:
                bucket: "{{ rke2_velero_s3_bucket }}"
                object: "{{ item.key }}"
                version_id: "{{ item.version_id }}"
                mode: delobj
              loop: "{{ bucket_versions.s3_keys | default([]) }}"
              when:
                - bucket_versions.s3_keys is defined
                - item.version_id is defined
                - item.version_id != 'null'
                - item.is_delete_marker | default(false)
              ignore_errors: true

        - name: Delete S3 bucket
          amazon.aws.s3_bucket:
            name: "{{ rke2_velero_s3_bucket }}"
            state: absent
            force: true
          ignore_errors: true

- name: Include common destroy playbook
  import_playbook: ../common/destroy.yml
