---
- name: Import component playbook
  import_playbook: pokerops.rke2.init
  vars:
    rke2_skip_deploy: false

- name: Add ingress endpoints to local hostfile
  hosts: rke2_server
  run_once: true
  vars_files:
    - ../../playbooks/vars/main.yml
  tasks:
    - name: Query cluster ingresses
      ansible.builtin.command:
        cmd: "/var/lib/rancher/rke2/bin/kubectl get ingresses -A -o json --kubeconfig /etc/rancher/rke2/rke2.yaml"
      register: _ingress_query
      changed_when: false
      become: true

    - name: Exit on partial ingress readiness
      ansible.builtin.meta: end_play
      vars:
        _ingress_data: "{{ _ingress_query.stdout | from_json }}"
        _ingress_all: "{{ _ingress_data['items'] }}"
        _ingress_lbs: "{{ _ingress_all | selectattr('status.loadBalancer', 'defined') | map(attribute='status.loadBalancer') }}"
        _ingress_ready: "{{ _ingress_lbs | selectattr('ingress', 'defined') | map(attribute='ingress') | list }}"
      when: (_ingress_all | length) == (_ingress_ready | length)

    - name: Set ingress facts
      ansible.builtin.set_fact:
        _ingress_hosts: "{{ _ingress_data['items'] | map(attribute='spec.rules') | map('map', attribute='host') }}"
        _ingress_endpoints: "{{ _ingress_data['items'] | map(attribute='status.loadBalancer.ingress') | map('map', attribute='ip') }}"
      vars:
        _ingress_data: "{{ _ingress_query.stdout | from_json }}"

    - name: Add ingress endpoints to local hostfile
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^{{ ' '.join(item.0) }}\\s+.*"
        line: "{{ item.1 | first }} {{ ' '.join(item.0) }}"
      loop_control:
        label: "{{ item | flatten | reverse | join(' - ') }}"
      loop: "{{ _ingress_hosts | zip(_ingress_endpoints) }}"
      delegate_to: localhost
      become: true
