---
- name: Prepare KVM guests
  hosts: all
  become: true
  tasks:
    - name: Debug apt configuration
      when: ansible_os_family == 'Debian'
      block:
        - name: Stat apt configuration
          ansible.builtin.stat:
            path: /etc/apt/sources.list
          register: _apt_config

        - name: Debug apt configuration
          when: _apt_config.stat.exists
          block:
            - name: Slurp apt configuration
              ansible.builtin.slurp:
                src: /etc/apt/sources.list.d/ubuntu.sources
              register: _apt_config_slurp

            - name: Debug apt configuration
              ansible.builtin.debug:
                msg: |
                  {{ _apt_config_slurp.content | b64decode }}

        - name: Stat apt configuration
          ansible.builtin.stat:
            path: /etc/apt/sources.list
          register: _apt_config

        - name: Debug apt configuration
          when: _apt_config.stat.exists
          block:
            - name: Slurp apt configuration
              ansible.builtin.slurp:
                src: /etc/apt/sources.list.d/ubuntu.sources
              register: _apt_config_slurp

            - name: Debug apt configuration
              ansible.builtin.debug:
                msg: |
                  {{ _apt_config_slurp.content | b64decode }}

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Install gpg agent
      ansible.builtin.apt:
        package: gpg-agent
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Install python3 binary redirection
      ansible.builtin.apt:
        name: python-is-python3
      when: ansible_os_family == 'Debian'

    - name: Disable ipv6
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_set: true
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Install multipath tools
      ansible.builtin.package:
        name: "{{ (ansible_os_family == 'Debian') | ternary(_multipath_deb, _multipath_rpm) }}"
      vars:
        _multipath_deb: multipath-tools
        _multipath_rpm: device-mapper-multipath

    - name: Check rke2_api_url parameter
      ansible.builtin.assert:
        that: rke2_api_url is defined
        fail_msg: "rke2_api_url must be defined"

    - name: Create api host file entry
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ _api_hostname }}.*"
        line: "{{ ansible_default_ipv4.address }} {{ _api_hostname }}"
      vars:
        _api_hostname: "{{ rke2_api_url | urlsplit('hostname') }}"

- name: Prepare KVM host
  hosts: localhost
  become: true
  tasks:
    - name: Create api host file entry
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ _api_hostname }}.*"
        line: "{{ _api_address }} {{ _api_hostname }}"
      vars:
        _api_hostname: "{{ rke2_api_url | urlsplit('hostname') }}"
        _api_address: "{{ hostvars[groups['rke2_server'].0]['ansible_default_ipv4']['address'] }}"
