---
- name: Create keel namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rke2_keel_chart.namespace }}"

- name: Deploy keel chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: keel
        namespace: kube-system
      spec:
        chart: "{{ rke2_keel_chart.name }}"
        targetNamespace: "{{ rke2_keel_chart.namespace }}"
        repo: "{{ rke2_keel_chart.repo }}"
        valuesContent: |-
          helmProvider:
            version: "v3"
