---
- name: Deploy longhorn application
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition: "{{ _longhorn_chart_application }}"
  vars:
    _longhorn_chart_application: "{{ _longhorn_chart_manifest | combine(_longhorn_chart_overrides, recursive=True) }}"
    _longhorn_chart_manifest: "{{ lookup('ansible.builtin.template', 'templates/longhorn.yml' ) | from_yaml }}"
    _longhorn_chart_overrides:
      spec:
        source:
          helm:
            valuesObject: "{{ rke2_longhorn_values }}"

- name: Deploy longhorn snapshotclass
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      kind: VolumeSnapshotClass
      apiVersion: snapshot.storage.k8s.io/v1
      metadata:
        name: longhorn-snapshots
        labels:
          velero.io/csi-volumesnapshot-class: "true"
      driver: driver.longhorn.io
      deletionPolicy: Retain
