---
- name: Verify ippool ranges
  ansible.builtin.assert:
    that: rke2_ippool_private is defined
    fail_msg: "rke2_ippool_private must be defined"
  run_once: true

- name: Create metallb namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rke2_metallb_chart.namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

- name: Deploy metallb chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: metallb
        namespace: kube-system
      spec:
        chart: "{{ rke2_metallb_chart.name }}"
        targetNamespace: "{{ rke2_metallb_chart.namespace }}"
        repo: "{{ rke2_metallb_chart.repo }}"

- name: Create metallb private pool
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "metallb-private"
        namespace: "{{ rke2_metallb_chart.namespace }}"
      spec:
        addresses:
          - "{{ rke2_ippool_private }}"
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"

- name: Create metallb public pool
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "metallb-public"
        namespace: "{{ rke2_metallb_chart.namespace }}"
      spec:
        addresses:
          - "{{ rke2_ippool_public }}"
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"
  when: rke2_ippool_public is defined

- name: Advertise metallb pools
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: metallb
        namespace: "{{ rke2_metallb_chart.namespace }}"
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"
