---
- name: Deploy longhorn chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition: "{{ lookup('ansible.builtin.template', '../../../argocd/templates/metallb.yml' ) | from_yaml }}"

- name: Verify ippool ranges
  ansible.builtin.assert:
    that: rke2_ippool_private is defined
    fail_msg: "rke2_ippool_private must be defined"
  run_once: true

- name: Create metallb private pool
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: metallb-private
        namespace: metallb-system
      spec:
        addresses:
          - "{{ rke2_ippool_private }}"
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"

- name: Create metallb public pool
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: metallb-public
        namespace: metallb-system
      spec:
        addresses:
          - "{{ rke2_ippool_public }}"
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"
  when: rke2_ippool_public is defined

- name: Advertise metallb pools
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: metallb
        namespace: metallb-system
  retries: "{{ _rke2_retry_num }}"
  delay: "{{ _rke2_retry_delay }}"
