---
- name: Deploy nginx private controller
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition: "{{ _nginx_chart_application }}"
  vars:
    _nginx_chart_application: "{{ _nginx_chart_manifest | combine(_nginx_chart_overrides, recursive=True) }}"
    _nginx_chart_manifest: "{{ lookup('ansible.builtin.template', 'templates/nginx.yml' ) | from_yaml }}"
    _nginx_chart_overrides:
      metadata:
        name: "nginx-private"
      spec:
        source:
          helm:
            valuesObject:
              controller:
                metrics:
                  enabled: true
                config:
                  annotations-risk-level: "Critical"
                allowSnippetAnnotations: true
                ingressClass: nginx-private
                ingressClassResource:
                  default: true
                  name: "nginx-private"
                  controllerValue: "k8s.io/nginx-private"
                  annotations:
                    cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
                service:
                  annotations:
                    metallb.universe.tf/address-pool: "metallb-private"

- name: Deploy nginx public controller
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition: "{{ _nginx_chart_application }}"
  vars:
    _nginx_chart_application: "{{ _nginx_chart_manifest | combine(_nginx_chart_overrides, recursive=True) }}"
    _nginx_chart_manifest: "{{ lookup('ansible.builtin.template', 'templates/nginx.yml' ) | from_yaml }}"
    _nginx_chart_overrides:
      metadata:
        name: "nginx-public"
      spec:
        source:
          helm:
            valuesObject:
              controller:
                metrics:
                  enabled: true
                config:
                  annotations-risk-level: "Critical"
                allowSnippetAnnotations: true
                ingressClass: nginx-public
                ingressClassResource:
                  name: "nginx-public"
                  controllerValue: "k8s.io/nginx-public"
                  annotations:
                    cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
                service:
                  annotations:
                    metallb.universe.tf/address-pool: "metallb-public"
  when: rke2_ippool_public is defined
