---
- name: Create reflector namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rke2_reflector_chart.namespace }}"

- name: Deploy reflector chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: reflector
        namespace: kube-system
      spec:
        chart: "{{ rke2_reflector_chart.name }}"
        targetNamespace: "{{ rke2_reflector_chart.namespace }}"
        repo: "{{ rke2_reflector_chart.repo }}"
