---
- name: Create sealed-secrets namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rke2_sealedsecrets_chart.namespace }}"

- name: Deploy sealed-secrets chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: sealed-secrets
        namespace: kube-system
      spec:
        chart: "{{ rke2_sealedsecrets_chart.name }}"
        targetNamespace: "{{ rke2_sealedsecrets_chart.namespace }}"
        repo: "{{ rke2_sealedsecrets_chart.repo }}"
        valuesContent: |-
          fullnameOverride: sealed-secrets-controller
