---
- name: Create cluster secret namespaces
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
  loop: "{{ rke2_secrets | map(attribute='namespace') | unique }}"

- name: Manage cluster secrets
  kubernetes.core.k8s:
    state: "{{ item.state | default('present') }}"
    kubeconfig: "{{ rke2_config_path }}"
    apply: true
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata: "{{ item.metadata | default({}) }}"
      type: "{{ item.type | default('Opaque') }}"
      data: "{{ item.data }}"
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ rke2_secrets }}"
  no_log: true
