---
- name: Create strimzi namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rke2_strimzi_chart.namespace }}"

- name: Deploy strimzi chart
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: strimzi
        namespace: kube-system
      spec:
        chart: "{{ rke2_strimzi_chart.name }}"
        targetNamespace: "{{ rke2_strimzi_chart.namespace }}"
        repo: "{{ rke2_strimzi_chart.repo }}"
        valuesContent: |-
          watchAnyNamespace: true
