---
- name: Deploy Vector operator
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ rke2_config_path }}"
    resource_definition: "{{ lookup('ansible.builtin.template', 'templates/vector.yml') }}"
