---
rke2_argocd_hostname: "argocd.{{ rke2_cluster_name }}"
rke2_argocd_exec_timeout: "3m"
rke2_argocd_chart:
  name: "argo-cd"
  namespace: "argocd"
  repo: "https://argoproj.github.io/argo-helm"
  release: "8.0.17"
rke2_argocd_redis_ha_enabled: true
rke2_argocd_controller_replicas: 2
rke2_argocd_server_replicas: 2
rke2_argocd_reposerver_replicas: 2
rke2_argocd_applicationset_replicas: 2
rke2_argocd_values:
  redis-ha:
    enabled: "{{ rke2_argocd_redis_ha_enabled }}"
  controller:
    replicas: "{{ rke2_argocd_controller_replicas }}"
  server:
    replicas: "{{ rke2_argocd_server_replicas }}"
    ingress:
      enabled: true
      https: true
      ingressClassName: nginx-private
      hostname: "{{ rke2_argocd_hostname }}"
      annotations:
        cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      tls: true
    certificate:
      enabled: true
      domain: "{{ rke2_argocd_hostname }}"
      issuer:
        name: "{{ rke2_certmanager_issuer_name }}"
        kind: ClusterIssuer
  repoServer:
    replicas: "{{ rke2_argocd_reposerver_replicas }}"
  applicationSet:
    replicas: "{{ rke2_argocd_applicationset_replicas }}"
  configs: "{{ rke2_argocd_values_configs | default({}) }}"
  global:
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: "{{ rke2_argocd_exec_timeout }}"
rke2_argocd_apps_deploy: true
rke2_argocd_apps_chart:
  name: "argocd-apps"
  namespace: "argocd"
  repo: "https://argoproj.github.io/argo-helm"
  release: "2.0.2"
rke2_argocd_apps_pokerops_revision: 0.4.14
rke2_argocd_apps_values_extra: {}
rke2_argocd_apps_directory_include: "{*.yml,*.yaml}"
rke2_argocd_apps_values_base:
  applications:
    cluster:
      project: default
      source:
        repoURL: https://github.com/pokerops/ansible-collection-rke2.git
        targetRevision: "{{ rke2_argocd_apps_pokerops_revision }}"
        path: argocd/applications/
        directory:
          recurse: false
          include: "{{ rke2_argocd_apps_directory_include }}"
          exclude: "{{ rke2_argocd_apps_directory_exclude | default(omit) }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
      revisionHistoryLimit:
      info:
        - name: url
          value: https://github.com/pokerops/ansible-collection-rke2
rke2_argocd_apps_values:
  "{{ rke2_argocd_apps_values_base | combine(rke2_argocd_apps_values_extra,
  recursive=True) }}"
