---
rke2_longhorn_chart:
  name: longhorn
  namespace: longhorn-system
  repo: "https://charts.longhorn.io"
  release: "1.9.0"
  last_checked: "2025-05-27T18:24:48-06:00"
_rke2_longhorn_values: "{{ rke2_longhorn_values | default({}) }}"
