---
rke2_longhorn_hostname: "longhorn.{{ rke2_cluster_name }}"
rke2_longhorn_ingress_class: "{{ rke2_nginx_controller_deploy | bool | ternary('nginx-private', 'traefik-private') }}"
rke2_longhorn_snapshot_retention: Retain
rke2_longhorn_values:
  ingress:
    ingressClassName: "{{ rke2_longhorn_ingress_class }}"
    host: "{{ rke2_longhorn_hostname }}"
    tlsSecret: "{{ rke2_longhorn_hostname }}"
    annotations:
      cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
