---
rke2_longhorn_hostname: "longhorn.{{ rke2_cluster_name }}"
rke2_longhorn_values:
  ingress:
    ingressClassName: nginx-private
    host: "{{ rke2_longhorn_hostname }}"
    tlsSecret: "{{ rke2_longhorn_hostname }}"
    annotations:
      cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
