---
rke2_longhorn_hostname: "longhorn.{{ rke2_cluster_name }}"
rke2_longhorn_chart:
  name: longhorn
  namespace: longhorn-system
  repo: "https://charts.longhorn.io"
  release: "1.9.0"
  last_checked: "2025-05-27T18:24:48-06:00"
rke2_longhorn_values:
  persistence:
    defaultClass: true
  ingress:
    enabled: true
    ingressClassName: nginx-private
    host: "{{ rke2_longhorn_hostname }}"
    tls: true
    tlsSecret: "{{ rke2_longhorn_hostname }}"
    secureBackends: true
    annotations:
      cert-manager.io/cluster-issuer: "{{ rke2_certmanager_issuer_name }}"
