---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cnpg
  namespace: kube-system
spec:
  chart: cloudnative-pg
  targetNamespace: gnpg-system
  createNamespace: true
  repo: https://cloudnative-pg.github.io/charts
  version: "0.24.0"
