---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gatekeeper
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  chart: gatekeeper
  targetNamespace: gatekeeper
  createNamespace: true
  repo: https://open-policy-agent.github.io/gatekeeper/charts
  version: "0.0.0"
