---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keel
  namespace: kube-system
spec:
  chart: keel
  targetNamespace: keel-system
  createNamespace: true
  repo: https://charts.keel.sh
  version: "1.0.5"
  valuesContent: |-
    helmProvider:
      version: "v3"
