---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  chart: sealed-secrets
  targetNamespace: kube-system
  repo: https://bitnami-labs.github.io/sealed-secrets
  version: "2.17.3"
  valuesContent: |-
    fullnameOverride: sealed-secrets-controller
