---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: strimzi-kafka-operator
  namespace: kube-system
spec:
  chart: keel
  targetNamespace: strimzi
  createNamespace: true
  repo: https://strimzi.io/charts/
  version: "0.46.0"
  valuesContent: |-
    watchAnyNamespace: true
