---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://seaweedfs.github.io/seaweedfs-operator/
    chart: seaweedfs-operator
    targetRevision: "0.1.28"
    helm:
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
