---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master
    paths:
      - "molecule/**"
      - "playbooks/**"
      - "requirements.yml"
      - "roles.yml"
      - "roles/components/**"
      - "Makefile"
      - "pyproject.toml"
      - "poetry.lock"
      - "devbox.json"
      - "devbox.lock"
      - .github/workflows/molecule.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    name: molecule
    runs-on: libvirt
    strategy:
      matrix:
        scenario:
          - install
          - update
        image:
          - noble
          - jammy
        include:
          - scenario: components
            image: noble
          - scenario: velero
            image: noble

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true

      - name: Install test requirements
        run: devbox run -- make requirements

      - name: Debug test environment
        run: devbox run -- make debug

      - name: Run molecule tests
        run: devbox run -- make ${{ matrix.image }} test
        env:
          MOLECULE_REVISION: ${{ github.head_ref || github.ref_name }}
          MOLECULE_KVM_IMAGE: ${{ matrix.image }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          MOLECULE_OUTPUT_DIR: /tmp/logs
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.scenario }}-${{ matrix.image }}.log
          path: |
            /tmp/logs/*
          if-no-files-found: ignore
        if: always()
